# This file was generated by GoReleaser. DO NOT EDIT.
cask "bastion" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "bcf125ae9413b4137933e34a8563300bf2d752c15e4addb4e29709e8241e5bd0"
      url "https://github.com/BintangDiLangit/bastion/releases/download/v#{version}/bastion_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "75ef8c43d3e6e5b4c21a4d01f56092436e0cae2e761aca31453b4a4c235fc122"
      url "https://github.com/BintangDiLangit/bastion/releases/download/v#{version}/bastion_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "72c7472f3c4ea5a70adae0a901f78b9cb066cc52a191fdfbf4de603bbd18bc71"
      url "https://github.com/BintangDiLangit/bastion/releases/download/v#{version}/bastion_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a736c12c8ce10ff3a2c5b37c94438e6c9189fdd4845fe677903931862642adc7"
      url "https://github.com/BintangDiLangit/bastion/releases/download/v#{version}/bastion_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bastion"
  desc "Local-first security review for developers and AI coding agents"
  homepage "https://github.com/BintangDiLangit/bastion"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bastion"
  binary "bastion-mcp"
  binary "bastion-api"

  postflight do
    if OS.mac?
      ["bastion", "bastion-mcp", "bastion-api"].each do |bin|
        system_command "/usr/bin/xattr",
                       args: ["-dr", "com.apple.quarantine", "#{staged_path}/#{bin}"],
                       must_succeed: false
      end
    end
  end

  zap trash: [
      "~/.bastion",
    ]

end
